### ISSUE TITLE
Build errors related to change of raw pointer use

### ISSUE THREAD

**Issue by KoenTanghe** [aframires/freesound-juce#5]
Nothing urgent, just came across this while doing a quick test:

When trying to build the project with VS2019 (after opening and re-saving in a recent Projucer version), there are 3 build errors:

`Severity	Code	Description	Line	File	Path	Project	Suppression State
Error	C2440	'return': cannot convert from 'std::unique_ptr<juce::URL::DownloadTask,std::default_delete<juce::URL::DownloadTask>>' to 'juce::URL::DownloadTask *'	349	C:\Koen\Code\Various\freesound-juce\Source\FreesoundAPI.cpp	C:\Koen\Code\Various\freesound-juce\Source	FreesoundAPI-Demo_ConsoleApp	
Error	C2440	'return': cannot convert from 'std::unique_ptr<juce::URL::DownloadTask,std::default_delete<juce::URL::DownloadTask>>' to 'juce::URL::DownloadTask *'	355	C:\Koen\Code\Various\freesound-juce\Source\FreesoundAPI.cpp	C:\Koen\Code\Various\freesound-juce\Source	FreesoundAPI-Demo_ConsoleApp	
Error	C2440	'return': cannot convert from 'std::unique_ptr<juce::URL::DownloadTask,std::default_delete<juce::URL::DownloadTask>>' to 'juce::URL::DownloadTask *'	688	C:\Koen\Code\Various\freesound-juce\Source\FreesoundAPI.cpp	C:\Koen\Code\Various\freesound-juce\Source	FreesoundAPI-Demo_ConsoleApp	
`

This is due to JUCE having switched to using std::unique_ptr in more recent versions.
The easy fix is to change the above 3 API method implementations by adding .release() at the end in the return statements.
Or you could also return a std::unique_ptr (but then the "delete download" should probably go away in the main method of the example).

It might also be a good idea to update the .jucer file in the repository by re-saving the .jucer file with the Projucer built with a recent JUCE version.

**Comment by ffont** [comment]
Thanks for opening the issue. @aframires is that something you could maybe look into?

**Comment by aframires** [comment]
Sure!
